/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.util.Random;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSlider;

/**
 *
 * @author pedro
 */
public class TunelFrameAPP extends java.awt.Frame {

    /**
     * Creates new form SiloRobotsFrameAPP
     */
    public TunelFrameAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jSlider1.setMaximum(10);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(5);
        jSlider1.setOpaque(true);
        add(jSlider1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {

        TunelFrameAPP f = new TunelFrameAPP();
        f.setSize(800, 500);
        CanvasTunel cv = new CanvasTunel(800, 500);
        f.add(cv);
        f.setVisible(true);

        Random rnd = new Random(System.currentTimeMillis());

        Thread[] vehiculo = new Thread[2000];
        Tunel tq = new Tunel();
        rnd.setSeed(System.currentTimeMillis());

        for (int i = 0; i < 2000; i++) {
            if (rnd.nextInt(100) < 60) {
                vehiculo[i] = new Coche(tq,cv);
            } else {
                vehiculo[i] = new Thread(new Furgos(tq,cv));
            }
            vehiculo[i].start();
            
            Thread.sleep((f.jSlider1.getValue() + 1) * 500);
        }
        for (int i = 0; i < 2000; i++) {
            vehiculo[i].join();
        }

        Thread.sleep(2000);
        System.exit(0);
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
