/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pedro
 */
public class TunelFrameAPP extends java.awt.Frame {

    /**
     * Creates new form AgenciaFrameAPP
     */
    public TunelFrameAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {

        TunelFrameAPP f = new TunelFrameAPP();
        f.setSize(800, 600);
        CanvasTunel cv = new CanvasTunel(800, 600);
        f.add(cv);
        f.setVisible(true);
        cv.repaint();
        
       // TODO code application logic here
        Thread[] vehiculo = new Thread[20];
        Furgos comprador;
        Tunel tq = new Tunel(cv);
        Random rnd = new Random();
        rnd.setSeed(System.currentTimeMillis());
        try {

            for (int i = 0; i < 20; i++) {
                if (rnd.nextInt(100) < 40) {
                    vehiculo[i] = new Coche(tq);
                    vehiculo[i].start();
                } else {
                    comprador = new Furgos(tq);
                    vehiculo[i] = new Thread(comprador);
                    vehiculo[i].start();
                }
                Thread.sleep((rnd.nextInt(2) + 1) * 700);                
            }
            for (int i = 0; i < 20; i++) {
                vehiculo[i].join();
            }            
        } catch (InterruptedException ex) {


        }
        sleep(3);
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
