/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1;

import static java.lang.Thread.sleep;
import java.util.Random;

/**
 *
 * @author usuario
 */
public class Generador extends javax.swing.JFrame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        System.out.println("                                                   Comineza el programa                                   ");
      Generador gen=new Generador();
      int max=40;
      Thread[] hilos=new Thread[max];
      Random rand=new Random(System.currentTimeMillis());
      Terminal t=new Terminal();
      Asistente bus=new Asistente(t);
      bus.start();
      
        for (int i = 0; i < max; i++) {
            if(i%2==0){
                hilos[i]=new Thread(new Coche(t));
            }else{
                 hilos[i]=new Moto(t);
            }
            hilos[i].start();
        }
        
        for (int i = 0; i < max; i++) {
            hilos[i].join();
        }
        bus.interrupt();
       System.out.println("                                                   Finbaliza el programa                                   ");
       System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
