/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package practica5;

import static java.lang.Thread.sleep;
import java.util.Random;

/**
 *
 * @author usuario
 */
public class GeneradorFrame extends java.awt.Frame {
    
    /**private int maximo=10;
     * Creates new form GeneradorFrame
     */
    public GeneradorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException { 
       int maximo=20;
       Random r=new Random(System.currentTimeMillis());
       GeneradorFrame generador=new GeneradorFrame();
      
      Thread[] clientes= new Thread[maximo];
      generador.setSize(1000, 900);
      CentroCanvas canvas=new CentroCanvas(1000,900);
      generador.add(canvas);
      generador.setVisible(true);
      Rehabilita re;
      Centro centro=new Centro();
     
        for (int i = 0; i < maximo; i++) {
           if(r.nextInt(100) < 40){
               re =new Rehabilita(centro,canvas);
               clientes[i]=new Thread(re);
               clientes[i].start();
           } 
           else{
              clientes[i]=new Masaje(centro,canvas);
              clientes[i].start();
           }
           sleep((1+r.nextInt(2))*1000);
        }
        
        for (int i = 0; i < maximo; i++) {
            clientes[i].join();
        }
        System.out.println("Finaliza el Programa");
        System.exit(0);
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
