/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package javaapplication1;

import java.awt.Color;
import static java.lang.Thread.sleep;

/**
 *
 * @author usuario
 */
public class PilaFrame extends java.awt.Frame {

    /**
     * Creates new form PilaFrame
     */
    public PilaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        PilaFrame pf = new PilaFrame();
        CanvasPila cp = new CanvasPila(10);
        Pila p = new Pila(10,cp);
        Productor p1 = new Productor(p);
       
        Thread c1 = new Thread(new Consumidor(p));
       
        
        
        pf.setLocation(300,0);
        pf.add(cp);
        pf.pack();
        pf.setBackground(Color.red);
        pf.setVisible(true);
        
        
        
        p1.start();
        c1.start();
        
        
        p1.join();
        c1.join();
        
        
        sleep(3);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
