/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.awt.Color;
import java.util.Random;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSlider;

/**
 *
 * @author pedro
 */
public class TunelFrameAPP extends java.awt.Frame {

    private CanvasTunel cv;
    private Tunel tl;

    /**
     * Creates new form SiloRobotsFrameAPP
     */
    public TunelFrameAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFurgo = new javax.swing.JButton();
        jButtonCoche = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        jButtonFurgo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1/imagenes/furgo_peque.png"))); // NOI18N
        jButtonFurgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFurgoActionPerformed(evt);
            }
        });
        add(jButtonFurgo);
        jButtonFurgo.setBounds(240, 240, 86, 45);

        jButtonCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1/imagenes/coche_peque.png"))); // NOI18N
        jButtonCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCocheActionPerformed(evt);
            }
        });
        add(jButtonCoche);
        jButtonCoche.setBounds(100, 240, 86, 48);
        jButtonCoche.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButtonCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCocheActionPerformed
        // TODO add your handling code here:
        Thread coche = new Coche(tl, cv);
        coche.start();
    }//GEN-LAST:event_jButtonCocheActionPerformed

    private void jButtonFurgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFurgoActionPerformed
        // TODO add your handling code here:
        Thread furgo = new Thread(new Furgos(tl, cv));
        furgo.start();
    }//GEN-LAST:event_jButtonFurgoActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {

        int alto = 500, ancho = 800;
        TunelFrameAPP f = new TunelFrameAPP();
        f.setSize(800, 500);
        f.setBackground(new Color(183, 194, 197));
        f.cv = new CanvasTunel(800, 400);
        f.tl = new Tunel();

        f.cv.setLocation(0, 20);
        f.add(f.cv);
        f.jButtonCoche.setLocation(200, 430);
        f.jButtonFurgo.setLocation(400, 430);
        f.setVisible(true);

        Random rnd = new Random(System.currentTimeMillis());
        Thread[] vehiculo = new Thread[2000];
        Tunel tq = new Tunel();

        /*
        new Thread(
                new Runnable() {
            @Override
            public void run() {
                rnd.setSeed(System.currentTimeMillis());

                for (int i = 0; i < 2000; i++) {
                    if (rnd.nextInt(100) < 60) {
                        vehiculo[i] = new Coche(f.tl, f.cv);
                    } else {
                        vehiculo[i] = new Thread(new Furgos(f.tl, f.cv));
                    }
                    vehiculo[i].start();
                    try {
                        Thread.sleep(3000);
                    } catch (InterruptedException ex) {
                    }

                }
                for (int i = 0; i < 2000; i++) {
                    try {
                        vehiculo[i].join();
                    } catch (InterruptedException ex) {
                    }
                }
            }
        ;
    }
    ).start()
    ;
    */
    

        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCoche;
    private javax.swing.JButton jButtonFurgo;
    // End of variables declaration//GEN-END:variables
}
