/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.concurrent.Semaphore;

/**
 *
 * @author usuario
 */
public class Generador extends javax.swing.JFrame {

    private static Semaphore sLeche = new Semaphore(10);
    private static Semaphore sCafe = new Semaphore(10);
    private static Semaphore Salacafe = new Semaphore(3);
    private static Semaphore SalaLeche = new Semaphore(3);
    private static Semaphore Papelera = new Semaphore(1);

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        int max = 30;
        Random r = new Random(System.currentTimeMillis());
        Thread[] clientes = new Thread[30];
        Generador gen = new Generador();
        CavasCongreso cv = new CavasCongreso(600, 800);
        gen.setSize(620,1000);
        gen.add(cv);
        gen.setTitle("CanvasCongreso");
        gen.setVisible(true);

        Camarero cam = new Camarero(sCafe, sLeche, cv);
        Thread camarero = new Thread(cam);
        camarero.start();
        for (int i = 0; i < max; i++) {
            if (r.nextInt(100) < 50) {
                Manchado m = new Manchado(sCafe, sLeche, SalaLeche, Salacafe, Papelera, cv);
                clientes[i] = new Thread(m);
            } else {
                clientes[i] = new Cortado(sCafe, sLeche, SalaLeche, Salacafe, Papelera, cv);
            }
            clientes[i].start();
            sleep(500);
        }
        for (int i = 0; i < max; i++) {
            clientes[i].join();
        }
        camarero.interrupt();
        camarero.join();
        System.out.println("Finaliza el programa.");
        System.exit(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
