/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo_frame;

import java.awt.Color;

/**
 *
 * @author pedro
 */
public class EjemploFrameApp extends java.awt.Frame {

    /**
     * Creates new form EjemploFrameApp
     */
    public EjemploFrameApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {

        final int  ancho=400, alto=200;

        EjemploFrameApp elframe = new EjemploFrameApp();
        VistaCanvas vista = new VistaCanvas(ancho, alto);

        elframe.setSize(ancho, alto);
        //elframe.setBackground(Color.red);
        elframe.add(vista);

        elframe.setVisible(true);

        Recurso m1 = new Recurso(vista);

        Thread h1 = new Thread(new Sumador(m1, 0));
        Thread h2 = new Thread(new Sumador(m1, 1));
        Thread h3 = new Thread(new Sumador(m1, 1));

        h1.start();
        h2.start();
        h3.start();

        h1.join();
        h2.join();
        h3.join();

        Thread.sleep(2000);
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
