/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica7;

import static java.lang.Thread.sleep;
import java.util.Random;

/**
 *
 * @author wadad
 */
public class Generador extends javax.swing.JFrame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        Random rand = new Random(System.currentTimeMillis());
        Thread[] animales = new Thread[20];
        Generador gen = new Generador();
        CanvasComedor cv = new CanvasComedor();
        Comedero c = new Comedero();
        gen.setLocation(250, 50);
        gen.setSize(1000, 700);
        gen.setTitle("Canvas Comedor de gatos y perros");
        gen.add(cv);
        gen.setVisible(true);

        Gato gato = new Gato(cv, c);
        for (int i = 0; i < 20; i++) {
            if (rand.nextInt(100) + 1 < 50) {
                animales[i] = new Thread(gato);
            } else {
                animales[i] = new Perro(cv, c);
            }
            animales[i].start();
            sleep((rand.nextInt(1) + 1) * 1000);

        }

        for (int i = 0; i < 20; i++) {
            animales[i].join();
        }
        System.out.println("Finaliza el programa.");
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
